
#FROM nginx:stable-alpine
FROM nginx:stable

COPY bin/vhost.sh /var/www/bin/vhost.sh
COPY doc/nginx/vhost.template /var/www/doc/nginx/vhost.template
COPY doc/nginx/ez_params.d /etc/nginx/ez_params.d
COPY web/bundles /var/www/web/bundles
COPY web/css /var/www/web/css
COPY web/fonts /var/www/web/fonts
COPY web/js /var/www/web/js

#RUN mkdir /var/www
CMD /bin/bash -c "cd /var/www && bin/vhost.sh --template-file=doc/nginx/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"